on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - Ubuntu
        - Windows

jobs:
  runs-on: [self-hosted, "${{ github.event.inputs.chosen-os }}"]
    steps:
    - name: Install dependencies
    run: python -m pip install --upgrade pip setuptools wheel
    - name: Run server
    - run: Python 3 — python -m http. server 8000
